### **Numpy**

In [1]:
# Array operations , Multidimensional arrays , Numeric python 
# Array are of same data types where as list accepts various data types 

# converting an list to 1-d numpy array 
import numpy as np 

my_list=[2,4,6,8,10]
arr=np.array(my_list)

In [2]:
print(arr)

[ 2  4  6  8 10]


In [4]:
arr.shape

(5,)

In [5]:
my_list1=[2,4,6,8,10]
my_list2=[2,4,6,8,10]
my_list3=[2,4,6,8,10]
arr1=np.array([my_list1,my_list2,my_list3])

In [6]:
print(arr1)

[[ 2  4  6  8 10]
 [ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [7]:
arr1.shape

(3, 5)

In [8]:
arr.reshape(5,1)

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10]])

In [9]:
arr1.reshape(5,3)

array([[ 2,  4,  6],
       [ 8, 10,  2],
       [ 4,  6,  8],
       [10,  2,  4],
       [ 6,  8, 10]])

In [12]:
arr1[:2,1:3]

array([[4, 6],
       [4, 6]])

In [14]:
arrge= np.arange(0,10)
arrge

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arrge_step= np.arange(0,10,2)
arrge_step

array([0, 2, 4, 6, 8])

In [16]:
arrge_linspace= np.linspace(0,10,30)
arrge_linspace

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])